---
# tasks file for nginx

- name: install web service
  ansible.builtin.package:
    name: nginx
    state: present
    update_cache: yes
  notify: start nginx

- name: delete default config
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Configure NGINX
  ansible.builtin.template:
    src: ./templates/nginx_load_balancer.conf.j2
    dest: /etc/nginx/sites-available/load_balancer.conf
  notify: reload nginx

- name: Enable NGINX loadbalancer site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/load_balancer.conf
    dest: /etc/nginx/sites-enabled/load_balancer.conf
    state: link
  notify: reload nginx