version: '3'

services:
  
  rust-container:
    build:
      context: ./docker-containers/rust-container
      dockerfile: Dockerfile
    privileged: true
    networks:
      - common
    tty: true
    container_name: rust-container
    volumes:
      - webserver-executable:/reddy/executable
  
  ansible-container:
    build:
      context: ./docker-containers/ansible-container
      dockerfile: Dockerfile
    privileged: true
    networks:
      common:
        ipv4_address: 172.16.238.241
    tty: true
    container_name: ansible-container
    depends_on:
      - rust-container
    volumes:
      - .:/ansible
      - ssh-keys:/root/.ssh
      - webserver-executable:/reddy/executable

  web-server1:
    build:
      context: ./docker-containers/ubuntu-container
      dockerfile: Dockerfile
    privileged: true
    networks:
      - common
    tty: true
    container_name: web-server1
    volumes:
      - ssh-keys:/root/.ssh

  web-server2:
    build:
      context: ./docker-containers/ubuntu-container
      dockerfile: Dockerfile
    privileged: true
    networks:
      - common
    tty: true
    container_name: web-server2
    volumes:
      - ssh-keys:/root/.ssh
  
  redis-server1:
    build:
      context: ./docker-containers/ubuntu-container
      dockerfile: Dockerfile
    privileged: true
    networks:
      - common
    tty: true
    container_name: redis-server1
    volumes:
      - ssh-keys:/root/.ssh

  load-balancer:
    build:
      context: ./docker-containers/ubuntu-container
      dockerfile: Dockerfile
    privileged: true
    networks:
      - common
    ports:
      - 8080:80
    tty: true
    container_name: load-balancer
    volumes:
      - ssh-keys:/root/.ssh
  
  # https://docs.semui.co/administration-guide/installation#docker
  postgres:
    restart: unless-stopped
    image: postgres:14
    hostname: postgres
    volumes: 
     - semaphore-postgres:/var/lib/postgresql/data
    privileged: true
    networks:
      - common
    environment:
     POSTGRES_USER: semaphore
     POSTGRES_PASSWORD: semaphore
     POSTGRES_DB: semaphore
  
  semaphore:
    restart: unless-stopped
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    privileged: true
    container_name: semaphore-container
    networks:
      common:
        ipv4_address: 172.16.238.240
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: postgres
      SEMAPHORE_DB_PORT: 5432
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: admin
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=
      SEMAPHORE_LDAP_ACTIVATED: 'no'
      TZ: UTC
    depends_on:
      - postgres
      - rust-container
    volumes:
      - ssh-keys:/home/semaphore/.ssh
      - webserver-executable:/reddy/executable

networks:
  common:
    ipam:
      config:
        - subnet: 172.16.238.0/24

volumes:
  ssh-keys:
  semaphore-postgres:
  webserver-executable: