---
- name: Start the redis instance
  gather_facts: no
  hosts: rediserver
  
  tasks:

   - name: Ensure redis-server service is installed
     ansible.builtin.package:
      name: redis-server
      state: present
     notify: Restart redis-server service
    
   - name: Copy the redis.conf file into /etc/redis
     ansible.builtin.copy:
       src: ./files/redis.conf
       dest: /etc/redis/redis.conf
       owner: redis
       mode: 777
     notify: Restart redis-server service
  
  handlers:
   - name: Restart redis-server service
     ansible.builtin.service:
      name: redis-server
      state: restarted

- name: Run reddy webserver
  gather_facts: no
  hosts: webserver
  tasks:

   - name: Ensure /etc/reddy folder exists
     ansible.builtin.file:
     args:
       dest: /etc/reddy
       state: directory

   - name: Copy reddy executable
     ansible.builtin.copy:
      src: /reddy/executable/reddy
      dest: /etc/reddy/reddy
      mode: 777

   - name: Create .env file
     ansible.builtin.template:
        src: ./templates/env.j2
        dest: /etc/reddy/.env
     vars:
        redis_hostname: ubuntu-container3
  
   - name: Copy systemd service file
     ansible.builtin.copy:
      src: ./files/reddy.service
      dest: /etc/systemd/system/reddy.service
     notify:
        - Reload systemd
        - Restart reddy service
  
  handlers:

   - name: Reload systemd
     ansible.builtin.systemd:
      daemon_reload: yes

   - name: Restart reddy service
     ansible.builtin.service:
      name: reddy
      state: restarted

- name: Config nginx as a load balancer
  hosts: loadbalancer
  tasks:
  - name: install web service
    ansible.builtin.package:
      name: nginx
      state: present
      update_cache: yes
    notify: start nginx

  - name: delete default config
    ansible.builtin.file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: reload nginx

  - name: Configure NGINX
    ansible.builtin.template:
      src: nginx/nginx_load_balancer.conf.j2
      dest: /etc/nginx/sites-available/load_balancer.conf
    notify: reload nginx

  - name: Enable NGINX load balancer site
    ansible.builtin.file:
      src: /etc/nginx/sites-available/load_balancer.conf
      dest: /etc/nginx/sites-enabled/load_balancer.conf
      state: link
    notify: reload nginx

  handlers:
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: reload nginx
    ansible.builtin.service:
      name: nginx
      state: reloaded