---
- name: Start the redis instance
  gather_facts: no
  hosts: rediserver
  
  tasks:

   - name: Ensure redis-server service is installed
     ansible.builtin.package:
      name: redis-server
      state: present
    
   - name: Copy the redis.conf file into /etc/redis
     ansible.builtin.copy:
     args:
       src: ./files/redis.conf
       dest: /etc/redis/redis.conf
       owner: redis
       mode: 777
      
   - name: Restart the redis-server service to ensure it is running and apply configuration
     ansible.builtin.service:
      name: redis-server
      state: restarted

- name: Run reddy webserver
  gather_facts: no
  hosts: webserver

  tasks:

   - name: Ensure /etc/reddy folder exists
     ansible.builtin.file:
     args:
       dest: /etc/reddy
       state: directory

   - name: Copy reddy executable
     ansible.builtin.copy:
      src: ./reddy/target/debug/reddy
      dest: /etc/reddy/reddy
      mode: 777

   - name: Create .env file
     ansible.builtin.template:
        src: ./templates/env.j2
        dest: /etc/reddy/.env
     vars:
        redis_hostname: ubuntu-container3
  
   - name: Copy systemd service file
     ansible.builtin.copy:
      src: ./files/reddy.service
      dest: /etc/systemd/system/reddy.service

   - name: Reload systemd
     ansible.builtin.systemd:
      daemon_reload: yes

   - name: Restart reddy service
     ansible.builtin.service:
      name: reddy
      state: restarted