---
- name: Configure nginx as load balancer
  gather_facts: no
  hosts: loadbalancer
  roles:
    - nginx-firewall
    - nginx

- name: Configure the redis instances for the webservers
  gather_facts: no
  hosts: rediservers
  roles :
    - rediservers

- name: Configure reddy project as webserver
  gather_facts: no
  hosts: webserver
  roles :
    - webserver-firewall
    - webserver