---
- name: Start the redis instance
  gather_facts: no
  hosts: rediservers
  roles :
    - rediservers

- name: Run reddy webserver
  gather_facts: no
  hosts: webserver
  roles :
    - webserver

- name: Configure NGINX as a load balancer
  gather_facts: no
  hosts: loadbalancer
  roles:
    - nginx