---

- name: Install PostgreSQL
  hosts: all
  become: yes
  tasks:

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present 

    - name: Verify PostgreSQL installation
      command: psql --version
      register: psql_version_output
      ignore_errors: yes 

    - name: Display a successful installation message if PostgreSQL is installed
      debug:
        msg: "PostgreSQL installed successfully. Version: {{ psql_version_output.stdout }}"
      when: psql_version_output.rc == 0 
