---
   - name: Ensure redis service is installed
     ansible.builtin.package:
      name: redis
      state: present

   - name: Copy the redis.conf file into /etc/redis
     ansible.builtin.copy:
     args:
       src: ./files/redis.conf
       dest: /etc/redis/redis.conf
       owner: redis
       mode: 777

   - name: Restart the redis service to ensure it is running and apply configuration
     ansible.builtin.service:
      name: redis
      state: restarted